In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,22,333])
print(a)

[  1  22 333]


In [ ]:
print(a.shape)

(3,)


In [ ]:
print(a[0])

1
22
333


In [ ]:
print(a[1])

In [ ]:
print(a[2])

In [ ]:
a[0] = 11
print(a)

[ 11  22 333]


In [ ]:
b = np.array([[4,5,6],
              [7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [ ]:
b.shape

(2, 3)

In [ ]:
print(b[0,0])

4


In [ ]:
c = np.array([9.0, 8.7, 6.5])
print(c)

[9.  8.7 6.5]


In [ ]:
d = np.zeros((5,6))
print(d)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
e = np.ones((5,6))
print(e)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
f = np.full((3,3), 7.8)
print(f)

[[7.8 7.8 7.8]
 [7.8 7.8 7.8]
 [7.8 7.8 7.8]]


In [ ]:
g= np.random.random((4,4))
print(g)

[[0.21243056 0.4998238  0.46474266 0.24573327]
 [0.80314845 0.94159578 0.65609858 0.0559475 ]
 [0.80367609 0.35230391 0.91716958 0.03513166]
 [0.37717325 0.00882003 0.82166044 0.7435783 ]]


In [ ]:
i = np.array([[12,23,34],
              [45,56,67],
              [78,89,90]])
print(i)

[[12 23 34]
 [45 56 67]
 [78 89 90]]


In [ ]:
j = i[:2, 1:3]
print(j)

[[23 34]
 [56 67]]


In [ ]:
print(i[0,1])

23


In [ ]:
j[0,0]=75
print(i[0,1])
print (i)

75
[[ 1 75  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
k = np.array([[26,78], [51,42], [30,89]])
print(k)

[[26 78]
 [51 42]
 [30 89]]


In [ ]:
print(k>50)

[[False  True]
 [ True False]
 [False  True]]


In [ ]:
print(k[k>50])

[78 51 89]


In [ ]:
l=np.array([[1,2],
            [3,4]])
m=np.array([[5,6],
            [7,8]])
print(l+m)

[[ 6  8]
 [10 12]]


In [ ]:
print(np.add(l,m))

[[ 6  8]
 [10 12]]


In [ ]:
# Subtraction using math operators
print(l-m)

[[-4 -4]
 [-4 -4]]


In [ ]:
# Subtraction using NumPy functions
print(np.subtract(l,m))

[[-4 -4]
 [-4 -4]]


In [ ]:
# Multiplication using math operators
print(l*m)

[[ 5 12]
 [21 32]]


In [ ]:
print(np.multiply(l,m))

[[ 5 12]
 [21 32]]


In [ ]:
print(l/m)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.divide(l,m))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(l)
print(np.sum(l))
print(np.sum(l, axis=0)) #sum of columns
print(np.sum(l, axis=1)) #sum of rows

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
